security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        users_in_memory: { memory: null }

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            stateless: true
            provider: users_in_memory

            # Se for usar autenticação personalizada, adicione seu custom_authenticator
            # Exemplo:
            # custom_authenticator: App\Security\YourAuthenticator
            # entry_point: App\Security\YourAuthenticator

    access_control:
        # Permitir livre acesso para requisições OPTIONS (CORS)
        - { path: ^/, roles: PUBLIC_ACCESS }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
